package ConsomiTounsi.entities;


public enum Role { PRODUCTS_ADMIN , ACCOUNTS_ADMIN , ADVERTISEMENTS_ADMIN,
	DELIVERIES_ADMIN, CLAIMS_ADMIN,PRODUCTS_MANAGER , ACCOUNTS_MANAGER , ADVERTISEMENTS_MANAGER,
	DELIVERIES_MANAGER, CLAIMS_MANAGER,EVENT_MANAGER,MANAGER }

