package ConsomiTounsi.entities;

public enum WorkField {
    ARTS , ENTERTAINMENT , COMMUNICATION , EDUCATION
    , FARMING_FISHING_FORESTRY , HEALTH_AND_MEDECINE , LAW , SALES ,
    ADMINISTRATION_AND_MANAGEMENT , SOCIAL_SERVICE , SCIENCE_AND_TECHNOLOGY ,
    INSTALLATION_AND_REPAIR , ARCHITECTURE_AND_ENGINEERING
}
